name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
  tests:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: All tests
      run: make test_all
    - name: clean-up
      run: make clean
      
  coverage:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Coverage of all tests
      run: make test_cov_all
    - name: clean-up
      run: make clean
    
  
